### ISSUE TITLE
Custom color Property support for PhET-iO state

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#163]
While working in the state wrapper, I found this assertion in the B:B Compare screen:

```

Uncaught Error: Assertion failed: tried to removeListener on something that wasn't a listener
    at window.assertions.assertFunction (assert.js:43:13)
    at TinyProperty.removeListener (TinyEmitter.ts:263:7)
    at TinyProperty.unlink (TinyProperty.ts:150:10)
    at LocalizedStringProperty.unlink (ReadOnlyProperty.ts:466:23)
    at DynamicProperty.dispose (DynamicProperty.ts:287:55)
    at Disposable.dispose (Disposable.ts:50:22)
    at Object.cleanup (DensityAccordionBox.ts:71:22)
    at ReadoutListAccordionBox.ts:142:44
    at TinyEmitter.notifyLoop (TinyEmitter.ts:213:7)
    at TinyEmitter.emit (TinyEmitter.ts:196:14)
    at DensityAccordionBox.setReadoutItems (ReadoutListAccordionBox.ts:106:25)
    at BuoyancyBasicsCompareScreenView.ts:157:27
    at TinyProperty.notifyLoop (TinyEmitter.ts:213:7)
    at TinyProperty.emit (TinyEmitter.ts:185:18)
    at EnumerationProperty._notifyListeners (ReadOnlyProperty.ts:352:23)
    at PhaseCallback.listener (ReadOnlyProperty.ts:400:47)
    at PropertyStateHandler.attemptToApplyPhases (PropertyStateHandler.ts:278:41)
    at PropertyStateHandler.undeferAndNotifyProperties (PropertyStateHandler.ts:198:12)
    at PropertyStateHandler.ts:91:12
    at TinyEmitter.notifyLoop (TinyEmitter.ts:213:7)
```

To reproduce:
1. Compare screen in B:B in state wrapper
2. click "Same Density"
3. Adjust density slider
4. Press reset after downstream has set state.

The reason is that deserializing custom Materials doesn't necessarily preserve the colorProperty reference, so disposing the DynamicProperty linked below fails because the deserialized is a different reference.

Buggy dispose:
https://github.com/phetsims/density-buoyancy-common/blob/d1152bed1f7dee0c49d41ea3f93d7fc918a30375/js/buoyancy/view/DensityAccordionBox.ts#L65
https://github.com/phetsims/density-buoyancy-common/blob/d1152bed1f7dee0c49d41ea3f93d7fc918a30375/js/buoyancy/view/DensityAccordionBox.ts#L42-L44

Serialization code:
https://github.com/phetsims/density-buoyancy-common/blob/f60c8501e5b54546fa210c92e565cbb482eac344/js/common/model/Material.ts#L684-L685

I will need some help in debugging this.

**Comment by zepumph** [comment]
On hold until #268 is complete.

**Comment by zepumph** [comment]
Duplicate of https://github.com/phetsims/buoyancy-basics/issues/17. Closing

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
