### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#165]
While working on https://github.com/phetsims/density-buoyancy-common/issues/154, I saw that on B:B explore screen, switching the combo box values several times, including to custom then to a non-custom triggers this error:

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Array'
    |     index 0 -> object with constructor 'MaterialEnumeration'
    |     property '_enumeration' -> object with constructor 'Enumeration'
    --- property 'values' closes the circle
    at JSON.stringify (<anonymous>)
    at validate (validate.ts:31:36)
    at EnumerationProperty._notifyListeners (ReadOnlyProperty.ts:333:15)
    at EnumerationProperty.unguardedSet (ReadOnlyProperty.ts:296:14)
    at EnumerationProperty.set (ReadOnlyProperty.ts:276:12)
    at set value (Property.ts:54:11)
    at Mass.ts:359:43
    at TinyProperty.notifyLoop (TinyEmitter.ts:213:7)
    at TinyProperty.emit (TinyEmitter.ts:185:18)
    at Property._notifyListeners (ReadOnlyProperty.ts:352:23)
```

**Comment by samreid** [comment]
According to CT this error was introduced in https://github.com/phetsims/density-buoyancy-common/commit/a4159ba797ab1b698f7b752ac6b42e8ec24c1602

**Comment by samreid** [comment]
@zepumph pointed out that PVC is missing and hence materialToEnumeration.

**Comment by samreid** [comment]
I will also move MaterialEnumeration to a separate file.

**Comment by samreid** [comment]
Fixed, @zepumph want to spot check?

**Comment by zepumph** [comment]
I added a comment. Perhaps sync conversation is best? Let me know.

**Comment by samreid** [comment]
Thanks, I moved that last part to #176 and labeled for help wanted. Closing.
