### ISSUE TITLE
CT Assertion failed: tried to removeListener on something that wasn't a listener

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density-buoyancy-common#235]
```
buoyancy-basics : phet-io-state-fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/phet-io-wrappers/state/?sim=buoyancy-basics&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1719221791194%22%2C%22timestamp%22%3A1719222646657%7D
ERROR: Assertion failed: tried to removeListener on something that wasn't a listener
STACK: Error: Assertion failed: tried to removeListener on something that wasn't a listener
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/assert/js/assert.js:45:13)
    at assert (TinyEmitter.ts:263:6)
    at removeListener (TinyProperty.ts:150:9)
    at unlink (ReadOnlyProperty.ts:457:22)
    at unlink (DynamicProperty.ts:286:54)
    at call (Disposable.ts:50:21)
    at dispose (DensityAccordionBox.ts:65:19)
    at listener (TinyEmitter.ts:213:6)
    at notifyLoop (TinyEmitter.ts:196:13)
    at emit (ReadoutListAccordionBox.ts:105:24)
    at setReadoutItems (BuoyancyBasicsExploreScreenView.ts:146:36)
    at listener (TinyEmitter.ts:213:6)
    at notifyLoop (TinyEmitter.ts:185:17)
    at emit (ReadOnlyProperty.ts:343:22)
    at _notifyListeners (ReadOnlyProperty.ts:287:13)
    at unguardedSet (ReadOnlyProperty.ts:267:11)
    at set (DerivedProperty.ts:159:12)
    at listener (TinyEmitter.ts:213:6)
    at notifyLoop (TinyEmitter.ts:185:17)
    at emit (ReadOnlyProperty.ts:343:22)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1719221791194%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dbuoyancy-basics%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1719221791194%22%2C%22timestamp%22%3A1719222646657%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1719221791194%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dbuoyancy-basics%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1719221791194%22%2C%22timestamp%22%3A1719222646657%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/phet-io-wrappers/state/?sim=buoyancy-basics&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1719221791194%22%2C%22timestamp%22%3A1719222646657%7D
[ATTACHED] 
[NAVIGATED] about:blank
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/buoyancy-basics/buoyancy-basics_en.html?brand=phet-io&ea&postMessageOnError&sim=buoyancy-basics&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1719221791194%22%2C%22timestamp%22%3A1719222646657%7D&frameTitle=source
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/buoyancy-basics/buoyancy-basics_en.html?brand=phet-io&ea&postMessageOnError&sim=buoyancy-basics&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1719221791194%22%2C%22timestamp%22%3A1719222646657%7D&frameTitle=destination
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed:  tried to removeListener on something that wasn't a listener
[CONSOLE] Debug info: {
  "seed": 0.0367266630055878,
  "currentScreenName": "ExploreScreen"
}
[PAGE ERROR] Error: Error: Assertion failed: tried to removeListener on something that wasn't a listener
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/assert/js/assert.js:45:13)
    at TinyProperty.removeListener (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/TinyEmitter.js:222:7)
    at TinyProperty.unlink (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/TinyProperty.js:134:10)
    at LocalizedStringProperty.unlink (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/ReadOnlyProperty.js:361:23)
    at DynamicProperty.dispose (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/DynamicProperty.js:231:53)
    at Disposable.dispose (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/Disposable.js:42:22)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/density-buoyancy-common/js/buoyancy/view/DensityAccordionBox.js:41:20
    at TinyEmitter.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
    at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/TinyEmitter.js:161:14)
    at DensityAccordionBox.setReadoutItems (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/density-buoyancy-common/js/buoyancy/view/ReadoutListAccordionBox.js:61:25)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/density-buoyancy-common/js/buoyancy-basics/view/BuoyancyBasicsExploreScreenView.js:114:37
    at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
    at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/TinyEmitter.js:154:18)
    at DerivedProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/ReadOnlyProperty.js:254:23)
    at DerivedProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/ReadOnlyProperty.js:201:14)
    at DerivedProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/ReadOnlyProperty.js:183:12)
    at DerivedProperty.getDerivedPropertyListener (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/DerivedProperty.js:112:13)
    at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
    at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/TinyEmitter.js:154:18)
    at BooleanProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/ReadOnlyProperty.js:254:23)
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 6/24/2024, 3:36:31 AM

----------------------------------

buoyancy-basics : phet-io-state-fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/phet-io-wrappers/state/?sim=buoyancy-basics&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1719221791194%22%2C%22timestamp%22%3A1719232253523%7D
ERROR: Assertion failed: tried to removeListener on something that wasn't a listener
STACK: Error: Assertion failed: tried to removeListener on something that wasn't a listener
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/assert/js/assert.js:45:13)
    at assert (TinyEmitter.ts:263:6)
    at removeListener (TinyProperty.ts:150:9)
    at unlink (ReadOnlyProperty.ts:457:22)
    at unlink (DynamicProperty.ts:247:38)
    at listener (TinyEmitter.ts:213:6)
    at notifyLoop (TinyEmitter.ts:185:17)
    at emit (ReadOnlyProperty.ts:343:22)
    at _notifyListeners (ReadOnlyProperty.ts:391:46)
    at listener (PropertyStateHandler.ts:278:40)
    at attemptToApplyPhases (PropertyStateHandler.ts:198:11)
    at undeferAndNotifyProperties (PropertyStateHandler.ts:91:11)
    at listener (TinyEmitter.ts:213:6)
    at notifyLoop (TinyEmitter.ts:196:13)
    at emit (Emitter.ts:64:21)
    at emit (PhetioStateEngine.ts:265:24)
    at setState (PhetioStateEngine.ts:282:9)
    at setFullState (phetioEngine.ts:1158:33)
    at apply (phetioCommandProcessor.ts:429:50)
    at process (phetioCommandProcessor.ts:303:35)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1719221791194%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dbuoyancy-basics%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1719221791194%22%2C%22timestamp%22%3A1719232253523%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1719221791194%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dbuoyancy-basics%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&testInfo=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1719221791194%22%2C%22timestamp%22%3A1719232253523%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/phet-io-wrappers/state/?sim=buoyancy-basics&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1719221791194%22%2C%22timestamp%22%3A1719232253523%7D
[ATTACHED] 
[NAVIGATED] about:blank
[ATTACHED] 
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/buoyancy-basics/buoyancy-basics_en.html?brand=phet-io&ea&postMessageOnError&sim=buoyancy-basics&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1719221791194%22%2C%22timestamp%22%3A1719232253523%7D&frameTitle=source
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/buoyancy-basics/buoyancy-basics_en.html?brand=phet-io&ea&postMessageOnError&sim=buoyancy-basics&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1719221791194%22%2C%22timestamp%22%3A1719232253523%7D&frameTitle=destination
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed:  tried to removeListener on something that wasn't a listener
[CONSOLE] Debug info: {
  "seed": 0.831279489720935,
  "currentScreenName": "CompareScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "PopupParentNode: PreferencesDialog"
  ]
}
[PAGE ERROR] Error: Error: Assertion failed: tried to removeListener on something that wasn't a listener
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/assert/js/assert.js:45:13)
    at TinyProperty.removeListener (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/TinyEmitter.js:222:7)
    at TinyProperty.unlink (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/TinyProperty.js:134:10)
    at LocalizedStringProperty.unlink (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/ReadOnlyProperty.js:361:23)
    at DynamicProperty.onPropertyChange (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/DynamicProperty.js:195:37)
    at TinyProperty.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
    at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/TinyEmitter.js:154:18)
    at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/ReadOnlyProperty.js:254:23)
    at PhaseCallback.listener (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/ReadOnlyProperty.js:299:47)
    at PropertyStateHandler.attemptToApplyPhases (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/PropertyStateHandler.js:224:41)
    at PropertyStateHandler.undeferAndNotifyProperties (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/PropertyStateHandler.js:153:12)
    at http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/PropertyStateHandler.js:57:12
    at TinyEmitter.notifyLoop (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/TinyEmitter.js:176:7)
    at TinyEmitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/TinyEmitter.js:161:14)
    at Emitter.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/axon/js/Emitter.js:52:22)
    at PhetioStateEngine.setState (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/phet-io/js/PhetioStateEngine.js:247:25)
    at PhetioStateEngine.setFullState (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/phet-io/js/PhetioStateEngine.js:264:10)
    at PhetioEngine.implementation (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/phet-io/js/phetioEngine.js:989:34)
    at PhetioCommandProcessor.process (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:312:51)
    at getReturn (http://128.138.93.172/continuous-testing/ct-snapshots/1719221791194/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:181:29)
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 6/24/2024, 3:36:31 AM
```

**Comment by zepumph** [comment]
I guess we didn't get https://github.com/phetsims/buoyancy/issues/67 after all.

**Comment by AgustinVallejo** [comment]
Linking https://github.com/phetsims/buoyancy/issues/67 for a better paper trail. Closing this one.
