### ISSUE TITLE
Error: Impossible set state from iterate; unset state: {   "buoyancy.applicationsScreen.model.objects.boat.materialProperty":

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#301]
During #123 and https://github.com/phetsims/density-buoyancy-common/issues/300 I saw that Studio => Test failed with this error:

```
Error: Impossible set state from iterate; unset state: {
  "buoyancy.applicationsScreen.model.objects.boat.materialProperty": {
    "value": {
      "phetioID": "buoyancy.optionalTandem"
    },
    "validValues": [
      {
        "phetioID": "buoyancy.optionalTandem"
      }
    ],
    "units": null
  }
}
 {
  "buoyancy.applicationsScreen.model.objects.boat.materialProperty": {
    "value": {
      "phetioID": "buoyancy.optionalTandem"
    },
    "validValues": [
      {
        "phetioID": "buoyancy.optionalTandem"
      }
    ],
    "units": null
  }
}
    at PhetioStateEngine.iterate (PhetioStateEngine.ts:360:17)
    at PhetioStateEngine.setState (PhetioStateEngine.ts:261:31)
    at PhetioStateEngine.setFullState (PhetioStateEngine.ts:282:10)
    at PhetioEngine.implementation (phetioEngine.ts:1158:34)
    at PhetioCommandProcessor.process (phetioCommandProcessor.ts:432:51)
    at getReturn (phetioCommandProcessor.ts:306:36)
    at phetioCommandProcessor.ts:314:18
    at Array.map (<anonymous>)
    at PhetioCommandProcessor.processCommands (phetioCommandProcessor.ts:304:30)
    at phetioCommandProcessor.ts:245:35
```

**Comment by samreid** [comment]
Caused by https://github.com/phetsims/density-buoyancy-common/issues/282, I'll address it over there. Closing as duplicate
