### ISSUE TITLE
DebugView throws errors

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#321]
While testing the debug view in Buoyancy: Applications, it threw this error:

```
ApplicationsDebugView.ts:121 Uncaught TypeError: Cannot read properties of undefined (reading 'getMatrix')
    at displacementListener (ApplicationsDebugView.ts:121:67)
    at NumberProperty.link (ReadOnlyProperty.ts:439:5)
    at ApplicationsDebugMassNode.specialBoatCase (ApplicationsDebugView.ts:132:39)
    at new DebugMassNode (DebugView.ts:191:10)
    at new ApplicationsDebugMassNode (ApplicationsDebugView.ts:102:5)
    at ApplicationsDebugView.createDebugMassNode (ApplicationsDebugView.ts:81:12)
    at onMassAdded (DebugView.ts:68:29)
    at TinyEmitter.notifyLoop (TinyEmitter.ts:213:7)
    at TinyEmitter.emit (TinyEmitter.ts:196:14)
    at Emitter.emit (Emitter.ts:64:22)
displacementListener @ ApplicationsDebugView.ts:121
link @ ReadOnlyProperty.ts:439
specialBoatCase @ ApplicationsDebugView.ts:132
DebugMassNode @ DebugView.ts:191
ApplicationsDebugMassNode @ ApplicationsDebugView.ts:102
createDebugMassNode @ ApplicationsDebugView.ts:81
onMassAdded @ DebugView.ts:68
notifyLoop @ TinyEmitter.ts:213
emit @ TinyEmitter.ts:196
emit @ Emitter.ts:64
emitNotification @ createObservableArray.ts:172
push @ createObservableArray.ts:405
visibilityListener @ DensityBuoyancyModel.ts:188
notifyLoop @ TinyEmitter.ts:213
emit @ TinyEmitter.ts:185
_notifyListeners @ ReadOnlyProperty.ts:343
unguardedSet @ ReadOnlyProperty.ts:287
set @ ReadOnlyProperty.ts:267
getDerivedPropertyListener @ DerivedProperty.ts:159
notifyLoop @ TinyEmitter.ts:213
emit @ TinyEmitter.ts:185
_notifyListeners @ ReadOnlyProperty.ts:343
unguardedSet @ ReadOnlyProperty.ts:287
set @ ReadOnlyProperty.ts:267
set value @ Property.ts:54
(anonymous) @ BuoyancyApplicationsModel.ts:129
notifyLoop @ TinyEmitter.ts:213
emit @ TinyEmitter.ts:185
_notifyListeners @ ReadOnlyProperty.ts:343
unguardedSet @ ReadOnlyProperty.ts:287
set @ ReadOnlyProperty.ts:267
set @ Property.ts:65
(anonymous) @ RectangularRadioButton.ts:146
notifyLoop @ TinyEmitter.ts:213
emit @ TinyEmitter.ts:196
emit @ Emitter.ts:64
fire @ RectangularRadioButton.ts:182
(anonymous) @ RectangularRadioButton.ts:151
notifyLoop @ TinyEmitter.ts:213
emit @ TinyEmitter.ts:185
_notifyListeners @ ReadOnlyProperty.ts:343
unguardedSet @ ReadOnlyProperty.ts:287
set @ ReadOnlyProperty.ts:267
set @ Property.ts:65
(anonymous) @ ButtonModel.ts:191
notifyLoop @ TinyEmitter.ts:213
emit @ TinyEmitter.ts:185
_notifyListeners @ ReadOnlyProperty.ts:343
unguardedSet @ ReadOnlyProperty.ts:287
set @ ReadOnlyProperty.ts:267
set value @ Property.ts:54
onRelease @ PressListener.ts:754
execute @ PhetioAction.ts:162
release @ PressListener.ts:512
pointerUp @ PressListener.ts:858
dispatchToListeners @ Input.ts:1869
dispatchEvent @ Input.ts:1818
upEvent @ Input.ts:1622
Input.mouseUpAction.PhetioAction.phetioPlayback @ Input.ts:396
execute @ PhetioAction.ts:162
mouseUp @ Input.ts:1188
pointerUp @ Input.ts:1386
run @ BatchedDOMEvent.ts:65
fireBatchedEvents @ Input.ts:900
batchEvent @ Input.ts:856
batchWindowEvent @ BrowserEvents.js:344
onpointerup @ BrowserEvents.js:388Understand this error
561ApplicationsDebugView.ts:64 Uncaught TypeError: Cannot read properties of undefined (reading 'right')
    at ApplicationsDebugView.ts:64:40
    at Array.forEach (<anonymous>)
    at ApplicationsDebugView.step (ApplicationsDebugView.ts:63:82)
    at BuoyancyApplicationsScreenView.step (DensityBuoyancyScreenView.ts:746:38)
    at BuoyancyApplicationsScreenView.step (BuoyancyApplicationsScreenView.ts:459:11)
    at Sim.ts:454:19
    at PhetioAction.execute (PhetioAction.ts:162:17)
    at Sim.stepSimulation (Sim.ts:1063:31)
    at Sim.stepOneFrame (Sim.ts:1053:12)
    at Sim.runAnimationLoop (Sim.ts:1028:12)
```

**Comment by samreid** [comment]
Discovered in https://github.com/phetsims/density-buoyancy-common/issues/257

**Comment by samreid** [comment]
Fixed the main problem and a side problem in the commit.  Now it fuzzes a lot longer. After long enough, you will still get:

```
<br class="Apple-interchange-newline">
  | window.assertions.assertFunction | @ | assert.js:27
-- | -- | -- | --
  | computeWindingMap | @ | Graph.js:1458
  | computeSimplifiedFaces | @ | Graph.js:339
  | binaryResult | @ | Graph.js:1661
  | shapeDifference | @ | Shape.ts:1728
  | mutatePoolShape | @ | ApplicationsDebugView.ts:86

```

However, that kind of problem also haunts the scenery helper, and doesn't feel in scope for this release. Closing.
