### ISSUE TITLE
CT measured same as calculated

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density-buoyancy-common#326]
```
buoyancy : custom-wrapper : unbuilt
URL: http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/phet-io-sim-specific/repos/buoyancy/wrappers/buoyancy-tests/?sim=buoyancy&phetioDebug=true&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723187225182%7D
ERROR: Assertion failed: measured same as calculated
STACK: window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/assert/js/assert.js:45:13
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/assert/js/assert.js:45:13)
    at measuredWeightPropertyTest (http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/phet-io-sim-specific/repos/buoyancy/wrappers/buoyancy-tests/?sim=buoyancy&phetioDebug=true&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723187225182%7D:65:15)
    at async* (http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/phet-io-sim-specific/repos/buoyancy/wrappers/buoyancy-tests/?sim=buoyancy&phetioDebug=true&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723187225182%7D:69:11)
    at phetioClient (PhetioClient.ts:1794:28)
    at oldSimInitialized (PhetioClient.ts:1310:8)
    at listener (PhetioClient.ts:1031:8)
    at message (PhetioClient.ts:645:29)
    at dispatch (PhetioClient.ts:470:21)
    at addEventListener (PhetioClient.ts:494:11)
    at  (PhetioClient.ts:1775:27)
    at  (PhetioClient.ts:1772:11)
    at <unknown> (http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/phet-io-sim-specific/repos/buoyancy/wrappers/buoyancy-tests/?sim=buoyancy&phetioDebug=true&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723187225182%7D:68:29)
====================
FULL LOG:
[URL] http://127.0.0.1/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1723186773762%2Fphet-io-sim-specific%2Frepos%2Fbuoyancy%2Fwrappers%2Fbuoyancy-tests%2F%3Fsim%3Dbuoyancy%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue&duration=70000&testInfo=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723187225182%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1723186773762%2Fphet-io-sim-specific%2Frepos%2Fbuoyancy%2Fwrappers%2Fbuoyancy-tests%2F%3Fsim%3Dbuoyancy%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue&duration=70000&testInfo=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723187225182%7D
[ATTACHED] 
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/phet-io-sim-specific/repos/buoyancy/wrappers/buoyancy-tests/?sim=buoyancy&phetioDebug=true&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723187225182%7D
[CONSOLE] enabling assert
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/buoyancy/buoyancy_en.html?brand=phet-io&ea&postMessageOnError&sim=buoyancy&phetioDebug=true&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723187225182%7D
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/chipper/dist/js/scenery/js/util/Utils.js" line: 423}]
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed:  measured same as calculated
[DETACHED] http://127.0.0.1/continuous-testing/ct-snapshots/1723186773762/buoyancy/buoyancy_en.html?brand=phet-io&ea&postMessageOnError&sim=buoyancy&phetioDebug=true&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723187225182%7D
[CONSOLE] continuous-test-wrapper-error
[PAGE ERROR] Error: Assertion failed: measured same as calculated
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1723186773762%2Fphet-io-sim-specific%2Frepos%2Fbuoyancy%2Fwrappers%2Fbuoyancy-tests%2F%3Fsim%3Dbuoyancy%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue&duration=70000&testInfo=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723187225182%7D

id: "Sparky Node Firefox"
Snapshot from 8/9/2024, 12:59:33 AM

----------------------------------

buoyancy : custom-wrapper : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1723186773762/phet-io-sim-specific/repos/buoyancy/wrappers/buoyancy-tests/?sim=buoyancy&phetioDebug=true&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723190607015%7D
ERROR: Assertion failed: measured same as calculated
STACK: Error: Assertion failed: measured same as calculated
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1723186773762/assert/js/assert.js:45:13)
    at measuredWeightPropertyTest (http://128.138.93.172/continuous-testing/ct-snapshots/1723186773762/phet-io-sim-specific/repos/buoyancy/wrappers/buoyancy-tests/?sim=buoyancy&phetioDebug=true&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723190607015%7D:65:15)
    at async (http://128.138.93.172/continuous-testing/ct-snapshots/1723186773762/phet-io-sim-specific/repos/buoyancy/wrappers/buoyancy-tests/?sim=buoyancy&phetioDebug=true&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723190607015%7D:69:5)
====================
FULL LOG:
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1723186773762%2Fphet-io-sim-specific%2Frepos%2Fbuoyancy%2Fwrappers%2Fbuoyancy-tests%2F%3Fsim%3Dbuoyancy%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue&duration=70000&testInfo=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723190607015%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1723186773762%2Fphet-io-sim-specific%2Frepos%2Fbuoyancy%2Fwrappers%2Fbuoyancy-tests%2F%3Fsim%3Dbuoyancy%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue&duration=70000&testInfo=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723190607015%7D
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1723186773762/phet-io-sim-specific/repos/buoyancy/wrappers/buoyancy-tests/?sim=buoyancy&phetioDebug=true&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723190607015%7D
[CONSOLE] enabling assert
[ATTACHED] 
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1723186773762/buoyancy/buoyancy_en.html?brand=phet-io&ea&postMessageOnError&sim=buoyancy&phetioDebug=true&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723190607015%7D
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed:  measured same as calculated
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1723186773762/buoyancy/buoyancy_en.html?brand=phet-io&ea&postMessageOnError&sim=buoyancy&phetioDebug=true&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723190607015%7D
[PAGE ERROR] Error: Error: Assertion failed: measured same as calculated
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1723186773762/assert/js/assert.js:45:13)
    at measuredWeightPropertyTest (http://128.138.93.172/continuous-testing/ct-snapshots/1723186773762/phet-io-sim-specific/repos/buoyancy/wrappers/buoyancy-tests/?sim=buoyancy&phetioDebug=true&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723190607015%7D:65:15)
    at async http://128.138.93.172/continuous-testing/ct-snapshots/1723186773762/phet-io-sim-specific/repos/buoyancy/wrappers/buoyancy-tests/?sim=buoyancy&phetioDebug=true&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22custom-wrapper%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1723186773762%22%2C%22timestamp%22%3A1723190607015%7D:69:5
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 8/9/2024, 12:59:33 AM
```

**Comment by samreid** [comment]
Setting just the `position` is not sufficient to move a mass, the matrix must also be changed. In the commit, I set the entire state of the mass to be on the scale, and it is working much better. Closing.
