### ISSUE TITLE
GrabDragInteraction: Interactive highlight shows the grab cue

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#349]
This is not from keyboard nav, this is from mouse-based interactive highlight:

![image](https://github.com/user-attachments/assets/5d53b9d2-70b5-4dfb-8823-70753ebabfde)

**Comment by zepumph** [comment]
This patch solves it, but I couldn't get Typescript to recognize InteractiveHighlighting as a mixin. Perhaps @jessegreenberg may know what I did wrong.


<details>

```
Subject: [PATCH] spacing, https://github.com/phetsims/density-buoyancy-common/issues/209
---
Index: js/common/view/MassView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/MassView.ts b/js/common/view/MassView.ts
--- a/js/common/view/MassView.ts	(revision c492de80d65ce6deb59452ff7f05868b306dc5e0)
+++ b/js/common/view/MassView.ts	(date 1724190618862)
@@ -10,7 +10,7 @@
 import Vector3 from '../../../../dot/js/Vector3.js';
 import densityBuoyancyCommon from '../../densityBuoyancyCommon.js';
 import Mass from '../model/Mass.js';
-import { InteractiveHighlighting, KeyboardDragListener, Node, Path } from '../../../../scenery/js/imports.js';
+import { HighlightPath, InteractiveHighlighting, KeyboardDragListener, Node, Path } from '../../../../scenery/js/imports.js';
 import { Shape } from '../../../../kite/js/imports.js';
 import MassTagNode from './MassTagNode.js';
 import ConvexHull2 from '../../../../dot/js/ConvexHull2.js';
@@ -106,9 +106,10 @@
 
         this.focusableShapeProperty.value = shape;
 
-        if ( this.focusablePath.focusHighlight && this.focusablePath.focusHighlight instanceof Path ) {
-          this.focusablePath.focusHighlight.setShape( shape );
-        }
+        assert && assert( this.focusablePath.focusHighlight instanceof Path );
+        assert && assert( this.focusablePath.interactiveHighlight instanceof Path );
+        this.focusablePath.focusHighlight.setShape( shape );
+        this.focusablePath.interactiveHighlight.setShape( shape );
       }
 
       this.massTagNode && repositionMassTagNode();
@@ -117,6 +118,8 @@
     if ( mass.canMove ) {
       this.focusablePath = new InteractiveHighlightingPath( this.focusableShapeProperty, {
         accessibleName: this.mass.accessibleName,
+        focusHighlight: new HighlightPath( null ),
+        interactiveHighlight: new HighlightPath( null ),
         tagName: 'div',
         focusable: true
       } );

**Comment by jessegreenberg** [comment]
Hmm, would you need to declare the type for the subclass options like this?

<details>

```
Subject: [PATCH] Interrupt mouse/keyboard when one form of input starts
---
Index: js/common/view/MassView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/MassView.ts b/js/common/view/MassView.ts
--- a/js/common/view/MassView.ts	(revision c492de80d65ce6deb59452ff7f05868b306dc5e0)
+++ b/js/common/view/MassView.ts	(date 1724192220301)
@@ -10,7 +10,7 @@
 import Vector3 from '../../../../dot/js/Vector3.js';
 import densityBuoyancyCommon from '../../densityBuoyancyCommon.js';
 import Mass from '../model/Mass.js';
-import { InteractiveHighlighting, KeyboardDragListener, Node, Path } from '../../../../scenery/js/imports.js';
+import { HighlightPath, InteractiveHighlighting, InteractiveHighlightingOptions, KeyboardDragListener, Node, Path, PathOptions } from '../../../../scenery/js/imports.js';
 import { Shape } from '../../../../kite/js/imports.js';
 import MassTagNode from './MassTagNode.js';
 import ConvexHull2 from '../../../../dot/js/ConvexHull2.js';
@@ -25,6 +25,7 @@
 import sharedSoundPlayers from '../../../../tambo/js/sharedSoundPlayers.js';
 import GrabDragInteraction from '../../../../scenery-phet/js/accessibility/GrabDragInteraction.js';
 import Multilink from '../../../../axon/js/Multilink.js';
+import TProperty from '../../../../axon/js/TProperty.js';
 
 const INVERT_Y_TRANSFORM = ModelViewTransform2.createSinglePointScaleInvertedYMapping( Vector2.ZERO, Vector2.ZERO, 1 );
 
@@ -106,9 +107,11 @@
 
         this.focusableShapeProperty.value = shape;
 
-        if ( this.focusablePath.focusHighlight && this.focusablePath.focusHighlight instanceof Path ) {
-          this.focusablePath.focusHighlight.setShape( shape );
-        }
+        assert && assert( this.focusablePath.focusHighlight instanceof Path );
+        assert && assert( this.focusablePath.interactiveHighlight instanceof Path );
+
+        ( this.focusablePath.focusHighlight as HighlightPath ).setShape( shape );
+        ( this.focusablePath.interactiveHighlight as HighlightPath ).setShape( shape );
       }
 
       this.massTagNode && repositionMassTagNode();
@@ -117,6 +120,8 @@
     if ( mass.canMove ) {
       this.focusablePath = new InteractiveHighlightingPath( this.focusableShapeProperty, {
         accessibleName: this.mass.accessibleName,
+        focusHighlight: new HighlightPath( null ),
+        interactiveHighlight: new HighlightPath( null ),
         tagName: 'div',
         focusable: true
       } );
@@ -242,10 +247,16 @@
   }
 }
 
+type InteractiveHighlightingPathOptions = InteractiveHighlightingOptions & PathOptions;
+
 /**
  * Intermediate class to create a Path with InteractiveHighlightingNode.
  * @mixes InteractiveHighlighting
  */
-class InteractiveHighlightingPath extends InteractiveHighlighting( Path ) {}
+class InteractiveHighlightingPath extends InteractiveHighlighting( Path ) {
+  public constructor( shape: Shape | TProperty<Shape>, providedOptions: InteractiveHighlightingPathOptions ) {
+    super( shape, providedOptions );
+  }
+}
 
 densityBuoyancyCommon.register( 'MassView', MassView );
\ No newline at end of file
```
</details>

**Comment by zepumph** [comment]
Thanks. That was very helpful. I believe that this is done, since now we are providing a separate interactiveHighlight so that it doesn't use the focusHighlight (which has the the cue added to it by the grabDragInteraction). There is more to do, but it will be done over in https://github.com/phetsims/density-buoyancy-common/issues/209.

**Comment by samreid** [comment]
The commits here appear to correlate with a new CT error for projectile motion:

```
1724196000624

2865 / 2871 Tests Completed
9 Tests Failed

axon: 23bc36a7bc2c33b960d18e5f2c04d65510ffefd5 => 0306c6cd71629a9c4d27ed4a11b7635b3a4554ea
density-buoyancy-common: c2a27d07c1b9b039d8d47886893011cddd520ceb => b70f2d7a052911fd629901588d9e69c2f281fb5d
scenery: 5f2ca96daf4e8da358a464dba277d713c75de68c => 78547e14800658c60df7984ff3d6a84b7db316b0

```

<img width="1321" alt="image" src="https://github.com/user-attachments/assets/e7bbf64f-c089-4126-88f4-1d1c98e252cf">


```

projectile-motion : phet-io-fuzz : unbuilt
URL: http://127.0.0.1/continuous-testing/ct-snapshots/1724235526375/projectile-motion/projectile-motion_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-motion%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1724235526375%22%2C%22timestamp%22%3A1724235863747%7D&ea&brand=phet-io&phetioStandalone&fuzz
ERROR: QUERY: ea&brand=phet-io&phetioStandalone&fuzz
Error: Assertion failed: All descendants must be disposed by the next frame: projectileMotion.dragScreen.model.trajectoryGroup.trajectory_1.dataPoints.elementAddedEmitter
STACK: window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1724235526375/assert/js/assert.js:45:13
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1724235526375/assert/js/assert.js:45:13)
    at assert (PhetioObject.ts:826:20)
    at forEach (PhetioObject.ts:825:20)
    at listener (Timer.ts:33:10)
    at  (TinyEmitter.ts:213:16)
    at notifyLoop (TinyEmitter.ts:196:13)
    at emit (Sim.ts:1033:24)
    at requestAnimationFrame (Sim.ts:1018:11)

```

**Comment by samreid** [comment]
Fixed with @zepumph. Closing.
