### ISSUE TITLE
Nested strings keys are not translatable. 

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#4]
Please see https://github.com/phetsims/chipper/issues/999 for background, but basically this has always been the case, but the assertion was broken until yesterday. Thus this repo's sims will not build until there are no more nested string keys. 

Error on build:

```
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: nested strings are not allowed outside of a11y string object for key: massLabel.1a
at Object.getStringFromMap (/data/share/phet/continuous-testing/ct-snapshots/1611625402680/chipper/js/common/ChipperStringUtils.js:156:63)
at /data/share/phet/continuous-testing/ct-snapshots/1611625402680/chipper/js/grunt/getStringMap.js:207:46
at Array.forEach (<anonymous>:null:null)
at /data/share/phet/continuous-testing/ct-snapshots/1611625402680/chipper/js/grunt/getStringMap.js:202:15
at Array.forEach (<anonymous>:null:null)
at /data/share/phet/continuous-testing/ct-snapshots/1611625402680/chipper/js/grunt/getStringMap.js:201:23
at Array.forEach (<anonymous>:null:null)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1611625402680/chipper/js/grunt/getStringMap.js:153:24)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1611625402680/chipper/js/grunt/buildRunnable.js:132:21)
at /data/share/phet/continuous-testing/ct-snapshots/1611625402680/chipper/js/grunt/Gruntfile.js:254:11
at wrap (/data/share/phet/continuous-testing/ct-snapshots/1611625402680/chipper/js/grunt/Gruntfile.js:73:7)

```

Sorry for the inconvenience.

**Comment by jonathanolson** [comment]
Handled with the above commit, closing.
