### ISSUE TITLE
Config.density is not finite

### ISSUE THREAD

**Issue by marlitas** [phetsims/density-buoyancy-common#78]
From CT:

```
buoyancy : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1668968503243/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1668968503243%22%2C%22timestamp%22%3A1668984872961%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1668968503243/assert/js/assert.js:28:13)
at assert (Material.ts:82:14)
at (Material.ts:99:11)
at createCustomMaterial (Material.ts:119:20)
at createCustomSolidMaterial (MaterialMassVolumeControlNode.ts:219:44)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:65:10)
id: Bayes Puppeteer
Snapshot from 11/20/2022, 10:21:43 AM

----------------------------------

buoyancy : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1668968503243/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1668968503243%22%2C%22timestamp%22%3A1669012269132%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1668968503243/assert/js/assert.js:28:13)
at assert (Material.ts:82:14)
at (Material.ts:99:11)
at createCustomMaterial (Material.ts:119:20)
at createCustomSolidMaterial (MaterialMassVolumeControlNode.ts:219:44)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:65:10)
id: Bayes Puppeteer
Snapshot from 11/20/2022, 10:21:43 AM

----------------------------------

buoyancy : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1668968503243/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1668968503243%22%2C%22timestamp%22%3A1669024374001%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1668968503243/assert/js/assert.js:28:13)
at assert (Material.ts:82:14)
at (Material.ts:99:11)
at createCustomMaterial (Material.ts:119:20)
at createCustomSolidMaterial (MaterialMassVolumeControlNode.ts:219:44)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:65:10)
id: Bayes Puppeteer
Snapshot from 11/20/2022, 10:21:43 AM

----------------------------------

buoyancy : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1668968503243/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1668968503243%22%2C%22timestamp%22%3A1668972770574%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: reentry detected, value=92.4, oldValue=0.5
Error: Assertion failed: reentry detected, value=92.4, oldValue=0.5
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1668968503243/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:308:14)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:65:10)
at set (SliderTrack.ts:151:20)
at handleTrackEvent (SliderTrack.ts:168:8)
at _start (DragListener.ts:365:26)
at callback (PressListener.ts:729:16)
at apply (PhetioAction.ts:125:16)
id: Bayes Puppeteer
Snapshot from 11/20/2022, 10:21:43 AM
```

**Comment by marlitas** [comment]
@samreid and I investigated this assertion error and found that the code is trying to divide by zero in `MaterialMassVolumeControlNode.ts`.

This can be replicated by:
1. Applications ScreenView in Buoyancy
2. Drag Material Inside Volume slider to 0
3. Switch material to custom

We attempted a fix with this patch:

```diff
Index: js/common/view/MaterialMassVolumeControlNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/MaterialMassVolumeControlNode.ts b/js/common/view/MaterialMassVolumeControlNode.ts
--- a/js/common/view/MaterialMassVolumeControlNode.ts	(revision 335fa8b564a5b3eb4260de01ca2fe4b3c37a9e99)
+++ b/js/common/view/MaterialMassVolumeControlNode.ts	(date 1669048735568)
@@ -216,8 +216,9 @@
         userMassChanging = true;
 
         if ( materialProperty.value.custom ) {
+          const volume = Math.max( volumeProperty.value, 0.5 );
           materialProperty.value = Material.createCustomSolidMaterial( {
-            density: mass / volumeProperty.value
+            density: mass / volume
           } );
         }
         else {
Index: js/common/model/Material.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/Material.ts b/js/common/model/Material.ts
--- a/js/common/model/Material.ts	(revision 335fa8b564a5b3eb4260de01ca2fe4b3c37a9e99)
+++ b/js/common/model/Material.ts	(date 1669047379094)
@@ -79,7 +79,7 @@
       liquidColor: null
     }, providedConfig );
 
-    assert && assert( isFinite( config.density ) );
+    assert && assert( isFinite( config.density ), `config.density should be a finite number. config.density = ${config.density}` );
 
     this.nameProperty = config.nameProperty;
     this.identifier = config.identifier;

```

However ran into a DynamicProperty error that indicates a link is attempting to remove itself twice. We were unsure how to continue, the best way to factor out the 0.5 minimum, and if this guard should be exercised further upstream.

**Comment by samreid** [comment]
I added a proposed fix that works OK in local testing.  This should be evaluated before publication though.

**Comment by samreid** [comment]
The proposed fix seems sensible and is passing on CT. Closing.
