### ISSUE TITLE
CT: Reentry detected

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#83]
```
buoyancy : pan-and-zoom-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1695737466745/buoyancy/buoyancy_en.html?continuousTest=%7B%22test%22%3A%5B%22buoyancy%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1695737466745%22%2C%22timestamp%22%3A1695737916023%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=true
Uncaught Error: Assertion failed: reentry detected, value=[Range (min:0.5 max:10)], oldValue=[Range (min:0.5 max:10)]
Error: Assertion failed: reentry detected, value=[Range (min:0.5 max:10)], oldValue=[Range (min:0.5 max:10)]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1695737466745/assert/js/assert.js:28:13)
at assert (ReadOnlyProperty.ts:311:14)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (DerivedProperty.ts:157:12)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:54:10)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1695737466745%2Fbuoyancy%2Fbuoyancy_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dtrue&testInfo=%7B%22test%22%3A%5B%22buoyancy%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1695737466745%22%2C%22timestamp%22%3A1695737916023%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1695737466745%2Fbuoyancy%2Fbuoyancy_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dtrue&testInfo=%7B%22test%22%3A%5B%22buoyancy%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1695737466745%22%2C%22timestamp%22%3A1695737916023%7D
[NAVIGATED] about:blank
```

**Comment by samreid** [comment]
@zepumph and @jonathanolson and I pushed a proposed fix for this.

**Comment by zepumph** [comment]
We hope we covered this from using an actual equality comparison. Let's check back in on CT later.

**Comment by samreid** [comment]
This is no longer appearing on CT, closing.
